config/routes.rb
Spree::Core::Engine.add_routes do
  resources :contacts, :controller => 'contact_us/contacts', :only => [:new, :create]
  get 'contact-us' => 'contact_us/contacts#new', :as => :contact_us
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact

      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject

      EMAIL_REGEX = /\A
        [^\s@]+ # non-at-sign characters, at least one
          @     # at-sign
        [^\s.@] # non-at-sign and non-period character
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
         \.     # period
        [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
        [^\s.@] # non-at-sign and non-period character
      \z/x

      validates :email,   :format => { :with => EMAIL_REGEX },
                          :presence => true
      validates :message, :presence => true
      validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}
      validates :subject, :presence => {:if => Proc.new{SpreeContactUs.require_subject}}

      def initialize(attributes = {})
        [:email, :message, :name, :subject].each do |attribute|
          self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
        end
      end

      def save
        if self.valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver
          return true
        end
        return false
      end

      def persisted?
        false
      end

    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])
    status = verify_google_recptcha(SECRET_KEY,params['g-recaptcha-response'])
    if @contact.save && status
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, :notice => Spree.t('contact_us.notices.success'))
    else
      render :new
    end
  end

  def new
    @contact = Spree::ContactUs::Contact.new
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  private

  def accurate_title
    Spree.t(:contact_us_title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def verify_google_recptcha(secret_key,response)
    status = `curl “https://www.google.com/recaptcha/api/siteverify? secret=#{secret_key}&response=#{response}”`
    hash = JSON.parse(status)
    hash["success"] == true ? true : false
  end
end

app/views/spree/contact_us/contacts/new.html.erb
<% content_for :head do -%>
  <meta name="title" content="<%= Spree.t(:contact_us_title) %>">
<% end -%>

<% content_for :sidebar do 
   if "products" == @current_controller && @taxon %>
    <%#= render :partial => "spree/shared/filters" %>
  <% else %>
    <%#= render :partial => "spree/shared/taxonomies" %>
  <% end
 end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @contact } %>

<h1><%= Spree.t(:contact_us_title) %></h1>


<div class="row">
  <div class="col-md-12">
    <div id="map-outer" class="col-md-12">
      <div id="address" class="col-md-4">
        <h2><%= t :CUGroup%></h2>
        <address>
          <strong><%= raw t('footerCQ.Address') %></strong><br>
          <%= t 'footerCQ.ZipCodeAndArea' %><br>
          <%= t 'footerCQ.CityAndCountry' %><br>
          <%= t'footerCQ.TelfNumber'%><br>
          <%= t 'footerCQ.mailto'%>
        </address>
      </div>
      <div id="map-container" class="col-md-8">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3044.570746494746!2d-3.749150599999999!3d40.2630701!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd418aa406d23043%3A0xa00a761c8266ee50!2sCalle+Bembibre%2C+28%2C+28947+Fuenlabrada%2C+Madrid!5e0!3m2!1ses!2ses!4v1422984818951" width="100%" height="100%" frameborder="0" style="border:0"></iframe>
      </div>
    </div><!-- /map-outer -->
  </div>
</div> <!-- /row -->

<div class="row">

  <%= form_for @contact, :url => contacts_path, :html => { :novalidate => '', :class => 'form-horizontal'} do |f| %>
      <div class="col-md-12" id="name_email">
        <div class="col-md-6 input-group pull-left" id="name">
          <span class="input-group-addon">
            <i class="fa fa-user"></i>
          </span>
          <%= f.text_field :name, class: 'form-control required',:id =>  "name", :placeholder => "Name"  %>
        </div>
        <div class="col-md-6  input-group pull-right" id="email">
          <span class="input-group-addon">
            <i class="fa fa-envelope"></i>
          </span>
          <%= f.email_field :email, class: 'form-control required', :id => "email", :placeholder => "Email Address" %>
        </div>
      </div>
      <div class="col-md-12 col-xs-12" id="comments">
        <div class="col-md-12 input-group">
              <span class="input-group-addon">
                <i class="fa fa-pencil"></i>
              </span>
          <%= f.text_area :message, class: 'form-control required', :rows => "6", :id => "comments_area", :placeholder => "Your question or comment here" %>
        </div>
      </div>
      <div class="col-md-12 col-xs-12" id="recaptcha">
        <%= recaptcha_tags %>
      </div>
      <div class="col-md-12 col-xs-12" id="condition">
        <div class="col-md-12 input-group">
          <label class="checkbox required micro" id="label_contact_term_and_cond" for="contact_term_and_cond" required>
            <input type="checkbox" id="contact_term_and_cond" name="contact[term_and_cond]" required="required" value="1" />
            <%= Spree.t(:contact_term_and_cond) %>
          </label>
        </div>
      </div>
      <div class="col-md-12 col-xs-12" id="button_submit">
        <%= f.submit Spree.t(:submit), :alt => Spree.t(:submit), :class => 'btn btn-success', :id => 'contact_us_contact_submit', :title => Spree.t(:submit) %>
      </div>
  <% end %>
</div>